using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace azara.repository.Migrations
{
    public partial class POSInventoryDemo_Added : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "POSInventoryDemo",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ListId = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TimeCreated = table.Column<DateTime>(type: "datetime2", nullable: true),
                    TimeModified = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ALU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Attribute = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    COGSAccount = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cost = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    DepartmentCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DepartmentListID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Desc1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IncomeAccount = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsBelowReorder = table.Column<bool>(type: "bit", nullable: true),
                    IsEligibleForCommission = table.Column<bool>(type: "bit", nullable: true),
                    IsPrintingTags = table.Column<bool>(type: "bit", nullable: true),
                    IsUnorderable = table.Column<bool>(type: "bit", nullable: true),
                    ItemNumber = table.Column<int>(type: "int", nullable: false),
                    ItemType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Keywords = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LastReceived = table.Column<DateTime>(type: "datetime2", nullable: true),
                    MarginPercent = table.Column<int>(type: "int", nullable: false),
                    MarkupPercent = table.Column<int>(type: "int", nullable: false),
                    MSRP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OnHandStore01 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore02 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore03 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore04 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore05 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore06 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore07 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore08 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore09 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore10 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore11 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore12 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore13 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore14 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore15 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore16 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore17 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore18 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore19 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OnHandStore20 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OrderByUnit = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrderCost = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Price1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Price2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Price3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Price4 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Price5 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    QuantityOnCustomerOrder = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    QuantityOnHand = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    QuantityOnOrder = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    QuantityOnPendingOrder = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ReorderPoint = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ReorderPointStore01 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SellByUnit = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SerialFlag = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Size = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StoreExchangeStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitOfMeasure = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UPC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorListID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WebDesc = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WebPrice = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Manufacturer = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Weight = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    WebSKU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WebCategories = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitOfMeasure1ALU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitOfMeasure1MSRP = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure1NumberOfBaseUnits = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure1Price1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure1Price2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure1Price3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure1Price4 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure1Price5 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure1UnitOfMeasure = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitOfMeasure1UPC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitOfMeasure2ALU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitOfMeasure2MSRP = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure2NumberOfBaseUnits = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure2Price1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure2Price2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure2Price3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure2Price4 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure2Price5 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure2UnitOfMeasure = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitOfMeasure2UPC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitOfMeasure3ALU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitOfMeasure3MSRP = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure3NumberOfBaseUnits = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure3Price1 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure3Price2 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure3Price3 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure3Price4 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure3Price5 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    UnitOfMeasure3UnitOfMeasure = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnitOfMeasure3UPC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo2ALU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo2OrderCost = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    VendorInfo2UPC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo2VendorListID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo3ALU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo3OrderCost = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    VendorInfo3UPC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo3VendorListID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo4ALU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo4OrderCost = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    VendorInfo4UPC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo4VendorListID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo5ALU = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo5OrderCost = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    VendorInfo5UPC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VendorInfo5VendorListID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Image = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_POSInventoryDemo", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "POSInventoryDemo");
        }
    }
}
