using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace azara.repository.Migrations
{
    public partial class possalesentity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "POSSalesReceiptTMP",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    TxnID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TimeCreated = table.Column<DateTime>(type: "datetime2", nullable: true),
                    TimeModified = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Associate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cashier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comments = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CustomerListID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Discount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    DiscountPercent = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    HistoryDocStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ItemsCount = table.Column<int>(type: "int", nullable: false),
                    PriceLevelNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PromoCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    QuickBooksFlag = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SalesOrderTxnID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SalesReceiptNumber = table.Column<int>(type: "int", nullable: false),
                    SalesReceiptType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShipDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    StoreExchangeStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StoreNumber = table.Column<int>(type: "int", nullable: false),
                    Subtotal = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TaxAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TaxCategory = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TaxPercentage = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Total = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TrackingNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TxnDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    TxnState = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Workstation = table.Column<int>(type: "int", nullable: false),
                    BillingInformationCity = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationCompanyName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationCountry = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationFirstName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationLastName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationPhone2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationPhone3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationPhone4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationPostalCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationSalutation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationState = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BillingInformationStreet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationCity = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationCompanyName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationCountry = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationFullName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationPhone = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationPhone2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationPhone3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationPhone4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationPostalCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationShipBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationShipping = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ShippingInformationState = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingInformationStreet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderAccount01TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount01TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount02TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount02TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount03TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount03TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount04TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount04TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount05TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount05TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount06TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount06TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount07TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount07TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount08TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount08TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount09TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount09TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount10TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderAccount10TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCheck01CheckNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCheck01TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCheck02CheckNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCheck02TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCheck03CheckNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCheck03TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCheck04CheckNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCheck04TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCheck05CheckNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCheck05TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCheck06CheckNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCheck06TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCheck07CheckNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCheck07TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCheck08CheckNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCheck08TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCheck09CheckNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCheck09TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCheck10CheckNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCheck10TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCash01TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCash02TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCash03TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCash04TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCash05TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCash06TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCash07TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCash08TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCash09TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCash10TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCreditCard01CardName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCreditCard01TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCreditCard01TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCreditCard02CardName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCreditCard02TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCreditCard02TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCreditCard03CardName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCreditCard03TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCreditCard03TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCreditCard04CardName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCreditCard04TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCreditCard04TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCreditCard05CardName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderCreditCard05TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderCreditCard05TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDebitCard01Cashback = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDebitCard01TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDebitCard02Cashback = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDebitCard02TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDebitCard03Cashback = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDebitCard03TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDebitCard04Cashback = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDebitCard04TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDebitCard05Cashback = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDebitCard05TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDeposit01TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDeposit02TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDeposit03TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDeposit04TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderDeposit05TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift01TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift01GiftCertificateNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderGift02TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift02GiftCertificateNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderGift03TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift03GiftCertificateNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderGift04TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift04GiftCertificateNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderGift05TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift05GiftCertificateNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderGift06TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift06GiftCertificateNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderGift07TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift07GiftCertificateNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderGift08TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift08GiftCertificateNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderGift09TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift09GiftCertificateNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderGift10TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGift10GiftCertificateNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenderGiftCard01TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGiftCard01TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGiftCard02TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGiftCard02TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGiftCard03TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGiftCard03TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGiftCard04TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGiftCard04TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGiftCard05TenderAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TenderGiftCard05TipAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    FQSaveToCache = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_POSSalesReceiptTMP", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "POSSalesReceiptTMP");
        }
    }
}
