//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azara.client.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Massage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Massage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("azara.client.Shared.ResourceFiles.Massage", typeof(Massage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azara Account Password Is Changed.
        /// </summary>
        public static string email_sub_change_password {
            get {
                return ResourceManager.GetString("email_sub_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Verification Code Received.
        /// </summary>
        public static string email_sub_forgot_password {
            get {
                return ResourceManager.GetString("email_sub_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is now successfully verified.
        /// </summary>
        public static string email_verified {
            get {
                return ResourceManager.GetString("email_verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Received for email verification.
        /// </summary>
        public static string email_verify_otp_received {
            get {
                return ResourceManager.GetString("email_verify_otp_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email.
        /// </summary>
        public static string enter_valid_email {
            get {
                return ResourceManager.GetString("enter_valid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the terms and conditions.
        /// </summary>
        public static string error_accept_terms_conditions {
            get {
                return ResourceManager.GetString("error_accept_terms_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        public static string error_account_not_found {
            get {
                return ResourceManager.GetString("error_account_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address field is required..
        /// </summary>
        public static string error_address_required {
            get {
                return ResourceManager.GetString("error_address_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement not found.
        /// </summary>
        public static string error_advertisement_not_found {
            get {
                return ResourceManager.GetString("error_advertisement_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Birthday date..
        /// </summary>
        public static string error_birthdate_required {
            get {
                return ResourceManager.GetString("error_birthdate_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog not found.
        /// </summary>
        public static string error_blog_not_found {
            get {
                return ResourceManager.GetString("error_blog_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter city.
        /// </summary>
        public static string error_city_required {
            get {
                return ResourceManager.GetString("error_city_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is already exists.
        /// </summary>
        public static string error_code_exist {
            get {
                return ResourceManager.GetString("error_code_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is not same with password..
        /// </summary>
        public static string error_confirm_password_is_not_same_with_password {
            get {
                return ResourceManager.GetString("error_confirm_password_is_not_same_with_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password  field is required..
        /// </summary>
        public static string error_confirm_password_required {
            get {
                return ResourceManager.GetString("error_confirm_password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country  field is required..
        /// </summary>
        public static string error_country_required {
            get {
                return ResourceManager.GetString("error_country_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password is invalid.
        /// </summary>
        public static string error_current_password_invalid {
            get {
                return ResourceManager.GetString("error_current_password_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password  field is required field.
        /// </summary>
        public static string error_current_password_required {
            get {
                return ResourceManager.GetString("error_current_password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password should not same with new password.
        /// </summary>
        public static string error_current_password_same_with_new_password {
            get {
                return ResourceManager.GetString("error_current_password_same_with_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid date.
        /// </summary>
        public static string error_data_format {
            get {
                return ResourceManager.GetString("error_data_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already exists.
        /// </summary>
        public static string error_email_exist {
            get {
                return ResourceManager.GetString("error_email_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found..
        /// </summary>
        public static string error_email_not_found {
            get {
                return ResourceManager.GetString("error_email_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is not verified.
        /// </summary>
        public static string error_email_not_verified {
            get {
                return ResourceManager.GetString("error_email_not_verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  field is required.
        /// </summary>
        public static string error_email_required {
            get {
                return ResourceManager.GetString("error_email_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!, Please enter correct details.
        /// </summary>
        public static string error_enter_correct_details {
            get {
                return ResourceManager.GetString("error_enter_correct_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Login.
        /// </summary>
        public static string error_failed_to_login {
            get {
                return ResourceManager.GetString("error_failed_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name  field is required..
        /// </summary>
        public static string error_first_name_required {
            get {
                return ResourceManager.GetString("error_first_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the .jpg, .png &amp; .jpeg images.
        /// </summary>
        public static string error_image_fromat_invalid {
            get {
                return ResourceManager.GetString("error_image_fromat_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image field is required..
        /// </summary>
        public static string error_Image_required {
            get {
                return ResourceManager.GetString("error_Image_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size must be less than 5 mb.
        /// </summary>
        public static string error_image_size_invelid {
            get {
                return ResourceManager.GetString("error_image_size_invelid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image uploading failed.
        /// </summary>
        public static string error_image_upload_failed {
            get {
                return ResourceManager.GetString("error_image_upload_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email..
        /// </summary>
        public static string error_invalid_email {
            get {
                return ResourceManager.GetString("error_invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address &amp; password.
        /// </summary>
        public static string error_invalid_emailid_password {
            get {
                return ResourceManager.GetString("error_invalid_emailid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid firstname..
        /// </summary>
        public static string error_invalid_firstname {
            get {
                return ResourceManager.GetString("error_invalid_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid lasstname..
        /// </summary>
        public static string error_invalid_lastname {
            get {
                return ResourceManager.GetString("error_invalid_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Mobile number..
        /// </summary>
        public static string error_invalid_Mobile {
            get {
                return ResourceManager.GetString("error_invalid_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP.
        /// </summary>
        public static string error_invalid_otp {
            get {
                return ResourceManager.GetString("error_invalid_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain the Alphabet, Digits and Special charaters with atleast 8 characters..
        /// </summary>
        public static string error_invalid_password_format {
            get {
                return ResourceManager.GetString("error_invalid_password_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid zipcode.
        /// </summary>
        public static string error_invalid_zipcode {
            get {
                return ResourceManager.GetString("error_invalid_zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP is already whitelisted.
        /// </summary>
        public static string error_IP_is_already_whitelisted {
            get {
                return ResourceManager.GetString("error_IP_is_already_whitelisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string error_last_name_required {
            get {
                return ResourceManager.GetString("error_last_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile is already exists.
        /// </summary>
        public static string error_mobile_exist {
            get {
                return ResourceManager.GetString("error_mobile_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number  field is required..
        /// </summary>
        public static string error_mobile_number_required {
            get {
                return ResourceManager.GetString("error_mobile_number_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp Expired.
        /// </summary>
        public static string error_otp_expired {
            get {
                return ResourceManager.GetString("error_otp_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter he OTP.
        /// </summary>
        public static string error_otp_not_found {
            get {
                return ResourceManager.GetString("error_otp_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid password.
        /// </summary>
        public static string error_password_invalid {
            get {
                return ResourceManager.GetString("error_password_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is required..
        /// </summary>
        public static string error_password_required {
            get {
                return ResourceManager.GetString("error_password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category not found.
        /// </summary>
        public static string error_product_category_not_found {
            get {
                return ResourceManager.GetString("error_product_category_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string error_product_not_found {
            get {
                return ResourceManager.GetString("error_product_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string error_something_went_wrong {
            get {
                return ResourceManager.GetString("error_something_went_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter state.
        /// </summary>
        public static string error_state_required {
            get {
                return ResourceManager.GetString("error_state_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store not found.
        /// </summary>
        public static string error_store_not_found {
            get {
                return ResourceManager.GetString("error_store_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table is already in use.
        /// </summary>
        public static string error_table_is_in_used {
            get {
                return ResourceManager.GetString("error_table_is_in_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is already exists.
        /// </summary>
        public static string error_title_exist {
            get {
                return ResourceManager.GetString("error_title_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is Expired.
        /// </summary>
        public static string error_token_expired {
            get {
                return ResourceManager.GetString("error_token_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is deleted.
        /// </summary>
        public static string error_user_deleted {
            get {
                return ResourceManager.GetString("error_user_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already exists.
        /// </summary>
        public static string error_user_exist {
            get {
                return ResourceManager.GetString("error_user_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        public static string error_user_inactive {
            get {
                return ResourceManager.GetString("error_user_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already exists.
        /// </summary>
        public static string error_username_exist {
            get {
                return ResourceManager.GetString("error_username_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter zipcode.
        /// </summary>
        public static string error_zipcode_required {
            get {
                return ResourceManager.GetString("error_zipcode_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Request Has Been Performed Successfully..
        /// </summary>
        public static string ok_response_successful {
            get {
                return ResourceManager.GetString("ok_response_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string page_not_found {
            get {
                return ResourceManager.GetString("page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully reset your password!.
        /// </summary>
        public static string password_reset_successfully {
            get {
                return ResourceManager.GetString("password_reset_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is sent to  .
        /// </summary>
        public static string response_forgot_password {
            get {
                return ResourceManager.GetString("response_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string response_password_changed_successfully {
            get {
                return ResourceManager.GetString("response_password_changed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been performed successfully..
        /// </summary>
        public static string response_request_performed_successfully {
            get {
                return ResourceManager.GetString("response_request_performed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Sucsessfully !.
        /// </summary>
        public static string sucsess_login {
            get {
                return ResourceManager.GetString("sucsess_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup successfully!.
        /// </summary>
        public static string sucsess_signup {
            get {
                return ResourceManager.GetString("sucsess_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already exists..
        /// </summary>
        public static string user_already_exists {
            get {
                return ResourceManager.GetString("user_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login.
        /// </summary>
        public static string user_login_first {
            get {
                return ResourceManager.GetString("user_login_first", resourceCulture);
            }
        }
    }
}
