namespace azara.models.Entities.POSSales
{
    public class POSSalesReceipt
    {
        [Key, Required]
        public int Id { get; set; }
        public string? TxnID { get; set; }
        public DateTime? TimeCreated { get; set; }
        public DateTime? TimeModified { get; set; }
        public string? Associate { get; set; }
        public string? Cashier { get; set; }
        public string? Comments { get; set; }
        public string? CustomerListID { get; set; }
        public decimal? Discount { get; set; }
        public decimal? DiscountPercent { get; set; }
        public string? HistoryDocStatus { get; set; }
        public int ItemsCount { get; set; }
        public string? PriceLevelNumber { get; set; }
        public string? PromoCode { get; set; }
        public string? QuickBooksFlag { get; set; }
        public string? SalesOrderTxnID { get; set; }
        public int SalesReceiptNumber { get; set; }
        public string? SalesReceiptType { get; set; }
        public DateTime? ShipDate { get; set; }
        public string? StoreExchangeStatus { get; set; }
        public int StoreNumber { get; set; }
        public decimal? Subtotal { get; set; }
        public decimal? TaxAmount { get; set; }
        public string? TaxCategory { get; set; }
        public decimal? TaxPercentage { get; set; }
        public string? TenderType { get; set; }
        public decimal? Total { get; set; }
        public string? TrackingNumber { get; set; }
        public DateTime? TxnDate { get; set; }
        public string? TxnState { get; set; }
        public int Workstation { get; set; }
        public string? BillingInformationCity { get; set; }
        public string? BillingInformationCompanyName { get; set; }
        public string? BillingInformationCountry { get; set; }
        public string? BillingInformationFirstName { get; set; }
        public string? BillingInformationLastName { get; set; }
        public string? BillingInformationPhone { get; set; }
        public string? BillingInformationPhone2 { get; set; }
        public string? BillingInformationPhone3 { get; set; }
        public string? BillingInformationPhone4 { get; set; }
        public string? BillingInformationPostalCode { get; set; }
        public string? BillingInformationSalutation { get; set; }
        public string? BillingInformationState { get; set; }
        public string? BillingInformationStreet { get; set; }
        public string? ShippingInformationCity { get; set; }
        public string? ShippingInformationCompanyName { get; set; }
        public string? ShippingInformationCountry { get; set; }
        public string? ShippingInformationFullName { get; set; }
        public string? ShippingInformationPhone { get; set; }
        public string? ShippingInformationPhone2 { get; set; }
        public string? ShippingInformationPhone3 { get; set; }
        public string? ShippingInformationPhone4 { get; set; }
        public string? ShippingInformationPostalCode { get; set; }
        public string? ShippingInformationShipBy { get; set; }
        public decimal? ShippingInformationShipping { get; set; }
        public string? ShippingInformationState { get; set; }
        public string? ShippingInformationStreet { get; set; }
        public decimal? TenderAccount01TenderAmount { get; set; }
        public decimal? TenderAccount01TipAmount { get; set; }
        public decimal? TenderAccount02TenderAmount { get; set; }
        public decimal? TenderAccount02TipAmount { get; set; }
        public decimal? TenderAccount03TenderAmount { get; set; }
        public decimal? TenderAccount03TipAmount { get; set; }
        public decimal? TenderAccount04TenderAmount { get; set; }
        public decimal? TenderAccount04TipAmount { get; set; }
        public decimal? TenderAccount05TenderAmount { get; set; }
        public decimal? TenderAccount05TipAmount { get; set; }
        public decimal? TenderAccount06TenderAmount { get; set; }
        public decimal? TenderAccount06TipAmount { get; set; }
        public decimal? TenderAccount07TenderAmount { get; set; }
        public decimal? TenderAccount07TipAmount { get; set; }
        public decimal? TenderAccount08TenderAmount { get; set; }
        public decimal? TenderAccount08TipAmount { get; set; }
        public decimal? TenderAccount09TenderAmount { get; set; }
        public decimal? TenderAccount09TipAmount { get; set; }
        public decimal? TenderAccount10TenderAmount { get; set; }
        public decimal? TenderAccount10TipAmount { get; set; }
        public string? TenderCheck01CheckNumber { get; set; }
        public decimal? TenderCheck01TenderAmount { get; set; }
        public string? TenderCheck02CheckNumber { get; set; }
        public decimal? TenderCheck02TenderAmount { get; set; }
        public string? TenderCheck03CheckNumber { get; set; }
        public decimal? TenderCheck03TenderAmount { get; set; }
        public string? TenderCheck04CheckNumber { get; set; }
        public decimal? TenderCheck04TenderAmount { get; set; }
        public string? TenderCheck05CheckNumber { get; set; }
        public decimal? TenderCheck05TenderAmount { get; set; }
        public string? TenderCheck06CheckNumber { get; set; }
        public decimal? TenderCheck06TenderAmount { get; set; }
        public string? TenderCheck07CheckNumber { get; set; }
        public decimal? TenderCheck07TenderAmount { get; set; }
        public string? TenderCheck08CheckNumber { get; set; }
        public decimal? TenderCheck08TenderAmount { get; set; }
        public string? TenderCheck09CheckNumber { get; set; }
        public decimal? TenderCheck09TenderAmount { get; set; }
        public string? TenderCheck10CheckNumber { get; set; }
        public decimal? TenderCheck10TenderAmount { get; set; }
        public decimal? TenderCash01TenderAmount { get; set; }
        public decimal? TenderCash02TenderAmount { get; set; }
        public decimal? TenderCash03TenderAmount { get; set; }
        public decimal? TenderCash04TenderAmount { get; set; }
        public decimal? TenderCash05TenderAmount { get; set; }
        public decimal? TenderCash06TenderAmount { get; set; }
        public decimal? TenderCash07TenderAmount { get; set; }
        public decimal? TenderCash08TenderAmount { get; set; }
        public decimal? TenderCash09TenderAmount { get; set; }
        public decimal? TenderCash10TenderAmount { get; set; }
        public string? TenderCreditCard01CardName { get; set; }
        public decimal? TenderCreditCard01TenderAmount { get; set; }
        public decimal? TenderCreditCard01TipAmount { get; set; }
        public string? TenderCreditCard02CardName { get; set; }
        public decimal? TenderCreditCard02TenderAmount { get; set; }
        public decimal? TenderCreditCard02TipAmount { get; set; }
        public string? TenderCreditCard03CardName { get; set; }
        public decimal? TenderCreditCard03TenderAmount { get; set; }
        public decimal? TenderCreditCard03TipAmount { get; set; }
        public string? TenderCreditCard04CardName { get; set; }
        public decimal? TenderCreditCard04TenderAmount { get; set; }
        public decimal? TenderCreditCard04TipAmount { get; set; }
        public string? TenderCreditCard05CardName { get; set; }
        public decimal? TenderCreditCard05TenderAmount { get; set; }
        public decimal? TenderCreditCard05TipAmount { get; set; }
        public decimal? TenderDebitCard01Cashback { get; set; }
        public decimal? TenderDebitCard01TenderAmount { get; set; }
        public decimal? TenderDebitCard02Cashback { get; set; }
        public decimal? TenderDebitCard02TenderAmount { get; set; }
        public decimal? TenderDebitCard03Cashback { get; set; }
        public decimal? TenderDebitCard03TenderAmount { get; set; }
        public decimal? TenderDebitCard04Cashback { get; set; }
        public decimal? TenderDebitCard04TenderAmount { get; set; }
        public decimal? TenderDebitCard05Cashback { get; set; }
        public decimal? TenderDebitCard05TenderAmount { get; set; }
        public decimal? TenderDeposit01TenderAmount { get; set; }
        public decimal? TenderDeposit02TenderAmount { get; set; }
        public decimal? TenderDeposit03TenderAmount { get; set; }
        public decimal? TenderDeposit04TenderAmount { get; set; }
        public decimal? TenderDeposit05TenderAmount { get; set; }
        public decimal? TenderGift01TenderAmount { get; set; }
        public string? TenderGift01GiftCertificateNumber { get; set; }
        public decimal? TenderGift02TenderAmount { get; set; }
        public string? TenderGift02GiftCertificateNumber { get; set; }
        public decimal? TenderGift03TenderAmount { get; set; }
        public string? TenderGift03GiftCertificateNumber { get; set; }
        public decimal? TenderGift04TenderAmount { get; set; }
        public string? TenderGift04GiftCertificateNumber { get; set; }
        public decimal? TenderGift05TenderAmount { get; set; }
        public string? TenderGift05GiftCertificateNumber { get; set; }
        public decimal? TenderGift06TenderAmount { get; set; }
        public string? TenderGift06GiftCertificateNumber { get; set; }
        public decimal? TenderGift07TenderAmount { get; set; }
        public string? TenderGift07GiftCertificateNumber { get; set; }
        public decimal? TenderGift08TenderAmount { get; set; }
        public string? TenderGift08GiftCertificateNumber { get; set; }
        public decimal? TenderGift09TenderAmount { get; set; }
        public string? TenderGift09GiftCertificateNumber { get; set; }
        public decimal? TenderGift10TenderAmount { get; set; }
        public string? TenderGift10GiftCertificateNumber { get; set; }
        public decimal? TenderGiftCard01TenderAmount { get; set; }
        public decimal? TenderGiftCard01TipAmount { get; set; }
        public decimal? TenderGiftCard02TenderAmount { get; set; }
        public decimal? TenderGiftCard02TipAmount { get; set; }
        public decimal? TenderGiftCard03TenderAmount { get; set; }
        public decimal? TenderGiftCard03TipAmount { get; set; }
        public decimal? TenderGiftCard04TenderAmount { get; set; }
        public decimal? TenderGiftCard04TipAmount { get; set; }
        public decimal? TenderGiftCard05TenderAmount { get; set; }
        public decimal? TenderGiftCard05TipAmount { get; set; }
        public bool FQSaveToCache { get; set; }
    }
}
